# Generated by Django 3.1.6 on 2021-02-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpagegridcontent',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
    ]
