# Generated by Django 3.1.6 on 2021-02-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_firstpagegridcontent_isnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpagegrid',
            name='content_moving',
            field=models.BooleanField(default=False),
        ),
    ]
