# Generated by Django 3.1.6 on 2021-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_firstpagegrid_content_moving'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('short_description', models.CharField(max_length=255)),
                ('detailed_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
